### ISSUE TITLE
Add Culture field for IWebDriverConfiguration

### ISSUE THREAD

**Issue by alpag** [AlexanderOnTest/NetCoreWebDriverFactory#27]
You wrote an amazing article about Internationalization of WebDriver (https://alexanderontesting.com/2020/01/29/webdrivers-with-culture-testing-internationalisation/). It would be really great if IWebDriverConfiguration interface would be extended by field Culture.
The other ideas are incognito mode and mobile emulation.

**Comment by AlexanderOnTest** [comment]
This is now included from v4.x
